ActiveModel::Attribute::WithCastValue is a private constant in Rails 7.0
and so directly referencing the constant causes
NameError: private constant ActiveModel::Attribute::WithCastValue referenced