Fix wrong code in README
You were setting `a` to a `Fixnum` instead of an ActiveRecord Relation:
```ruby
b = a.page(1).per(20).size
NoMethodError: undefined method `page' for 5:Fixnum
```